/* CREATING DATABASE */

CREATE DATABASE LIBRARY_MANAGEMENT

/* CREATING BRANCH TABLE */

DROP TABLE IF EXISTS BRANCH
CREATE TABLE BRANCH
    (
	   BRANCH_ID VARCHAR(10) PRIMARY KEY, --SHOULD BE NOT NULL AND UNIQUE
	   MANAGER_ID VARCHAR(10),
	   BRANCH_ADDRESS VARCHAR(50),
	   CONTACT_NO VARCHAR(20)
	)

/* CREATING EMPLOYEE TABLE */

DROP TABLE IF EXISTS EMPLOYEE
CREATE TABLE EMPLOYEE
    (
	   EMP_ID VARCHAR(10) PRIMARY KEY, --SHOULD BE NOT NULL AND UNIQUE
	   EMP_NAME VARCHAR(30),
	   POSITION VARCHAR(15),
	   SALARY INT,
	   BRANCH_ID VARCHAR(25),
	   FOREIGN KEY(BRANCH_ID) REFERENCES BRANCH(BRANCH_ID) 
	)

/* CREATING BOOKS TABLE */

DROP TABLE IF EXISTS BOOKS
CREATE TABLE BOOKS
    (
	    ISBN VARCHAR(20) PRIMARY KEY, --SHOULD BE NOT NULL AND UNIQUE
		BOOKS_TITLE VARCHAR(70),
		CATEGORY VARCHAR(20),
		RENTAL_PRICE FLOAT,
		STATUS VARCHAR(20),
		AUTHOR VARCHAR(30),
		PUBLISHER VARCHAR(60)
	)

/* CREATING MEMBERS TABLE */

DROP TABLE IF EXISTS MEMBERS
CREATE TABLE MEMBERS
    (
	   MEMBER_ID VARCHAR(10) PRIMARY KEY, --SHOULD BE NOT NULL AND UNIQUE
       MEMBER_NAME VARCHAR(25),
	   MEMBER_ADDRESS VARCHAR(75),
	   REG_DATE DATE
	)

/* CREATING ISSUED_STATUS TABLE */

DROP TABLE IF EXISTS ISSUED_STATUS
CREATE TABLE ISSUED_STATUS
    (
       ISSUED_ID VARCHAR(10) PRIMARY KEY, --SHOULD BE NOT NULL AND UNQUIE
	   ISSUED_MEMBER_ID VARCHAR(10), 
	   ISSUED_BOOK_NAME VARCHAR(80),
	   ISSUED_DATE DATE,
	   ISSUED_BOOK_ISBN VARCHAR(30), 
	   ISSUED_EMP_ID VARCHAR(10),
	   FOREIGN KEY(ISSUED_MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
	   FOREIGN KEY(ISSUED_BOOK_ISBN) REFERENCES BOOKS(ISBN),
	   FOREIGN KEY(ISSUED_EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
	)

/* CREATING RETURN_STATUS TABLE */

DROP TABLE IF EXISTS RETURN_STATUS
CREATE TABLE RETURN_STATUS
    (
       RETURN_ID VARCHAR(10) PRIMARY KEY, --SHOULD BE NOT NULL AND UNIQUE
	   ISSUED_ID VARCHAR(10), 
	   RETURN_BOOK_NAME VARCHAR(80),
	   RETURN_DATE DATE,
	   RETURN_BOOK_ISBN VARCHAR(20),
	   FOREIGN KEY(ISSUED_ID) REFERENCES ISSUED_STATUS(ISSUED_ID) 
    )


